export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const INIT = '@@INIT';

export const LOGOUT = 'LOGOUT';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_LOADED = 'LOGIN_LOADED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_UPDATE_ERRORS = 'LOGIN_UPDATE_ERRORS';
export const LOGIN_UPDATE_EMAIL = 'LOGIN_UPDATE_EMAIL';
export const LOGIN_UPDATE_PASSWORD = 'LOGIN_UPDATE_PASSWORD';

export const USER_ADD_TOKEN = 'USER_ADD_TOKEN';
