export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const INIT = '@@INIT';

export const LOGOUT = 'LOGOUT';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_LOADED = 'LOGIN_LOADED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_UPDATE_ERRORS = 'LOGIN_UPDATE_ERRORS';
export const LOGIN_UPDATE_EMAIL = 'LOGIN_UPDATE_EMAIL';
export const LOGIN_UPDATE_PASSWORD = 'LOGIN_UPDATE_PASSWORD';

export const USER_ADD_TOKEN = 'USER_ADD_TOKEN';
export const USER_INFOS_LOADING = 'USER_INFOS_LOADING';
export const USER_INFOS_LOADED = 'USER_INFOS_LOADED';
export const USER_INFOS_ERROR = 'USER_INFOS_ERROR';

export const LIST_LOADING = 'LIST_LOADING';
export const LIST_LOADED = 'LIST_LOADED';
export const LIST_ERROR = 'LIST_ERROR';
export const LIST_CHANGE_TAB = 'LIST_CHANGE_TAB';
export const LIST_CHANGE_SEARCH = 'LIST_CHANGE_SEARCH';
export const LIST_PAGE_UPDATE = 'LIST_PAGE_UPDATE';
export const LIST_PAGE_SIZE_UPDATE = 'LIST_PAGE_SIZE_UPDATE';
export const LIST_SORTED_UPDATE = 'LIST_SORTED_UPDATE';

export const FOLDER_UPDATE_CHECK_POINT_LOADING = 'FOLDER_UPDATE_CHECK_POINT_LOADING';
export const FOLDER_UPDATE_CHECK_POINT_LOADED = 'FOLDER_UPDATE_CHECK_POINT_LOADED';
export const FOLDER_UPDATE_CHECK_POINT_ERROR = 'FOLDER_UPDATE_CHECK_POINT_ERROR';
export const FOLDER_LOADING = 'FOLDER_LOADING';
export const FOLDER_LOADED = 'FOLDER_LOADED';
export const FOLDER_ERROR = 'FOLDER_ERROR';
export const FOLDER_UPDATE_MOA_VALUE = 'FOLDER_UPDATE_MOA_VALUE';
export const FOLDER_CLEAN_MOA_VALUE = 'FOLDER_CLEAN_MOA_VALUE';
export const FOLDER_UPDATE_MOA_LOADING = 'FOLDER_UPDATE_MOA_LOADING';
export const FOLDER_UPDATE_MOA_LOADED = 'FOLDER_UPDATE_MOA_LOADED';
export const FOLDER_UPDATE_MOA_ERROR = 'FOLDER_UPDATE_MOA_ERROR';
export const FOLDER_UPDATE_MOE_VALUE = 'FOLDER_UPDATE_MOE_VALUE';
export const FOLDER_CLEAN_MOE_VALUE = 'FOLDER_CLEAN_MOE_VALUE';
export const FOLDER_UPDATE_MOE_LOADING = 'FOLDER_UPDATE_MOE_LOADING';
export const FOLDER_UPDATE_MOE_LOADED = 'FOLDER_UPDATE_MOE_LOADED';
export const FOLDER_UPDATE_MOE_ERROR = 'FOLDER_UPDATE_MOE_ERROR';
export const FOLDER_UPDATE_SITE_VALUE = 'FOLDER_UPDATE_SITE_VALUE';
export const FOLDER_CLEAN_SITE_VALUE = 'FOLDER_CLEAN_SITE_VALUE';
export const FOLDER_UPDATE_SITE_LOADING = 'FOLDER_UPDATE_SITE_LOADING';
export const FOLDER_UPDATE_SITE_LOADED = 'FOLDER_UPDATE_SITE_LOADED';
export const FOLDER_UPDATE_SITE_ERROR = 'FOLDER_UPDATE_SITE_ERROR';
export const FOLDER_ENDING_LOADING = 'FOLDER_ENDING_LOADING';
export const FOLDER_ENDING_LOADED = 'FOLDER_ENDING_LOADED';
export const FOLDER_ENDING_ERROR = 'FOLDER_ENDING_ERROR';
export const FOLDER_FILE_UPDATE_LOADING = 'FOLDER_FILE_UPDATE_LOADING';
export const FOLDER_FILE_UPDATE_LOADED = 'FOLDER_FILE_UPDATE_LOADED';
export const FOLDER_FILE_UPDATE_ERROR = 'FOLDER_FILE_UPDATE_ERROR';
export const FOLDER_FILE_ENDING_LOADING = 'FOLDER_FILE_ENDING_LOADING';
export const FOLDER_FILE_ENDING_LOADED = 'FOLDER_FILE_ENDING_LOADED';
export const FOLDER_FILE_ENDING_ERROR = 'FOLDER_FILE_ENDING_ERROR';

export const COMMENTS_LIST_LOADING = 'COMMENTS_LIST_LOADING';
export const COMMENTS_LIST_LOADED = 'COMMENTS_LIST_LOADED';
export const COMMENTS_LIST_ERROR = 'COMMENTS_LIST_ERROR';
export const UPDATE_NEW_COMMENT_MESSAGE = 'UPDATE_NEW_COMMENT_MESSAGE';
export const COMMENTS_POST_COMMENT_LOADING = 'COMMENTS_POST_COMMENT_LOADING';
export const COMMENTS_POST_COMMENT_LOADED = 'COMMENTS_POST_COMMENT_LOADED';
export const COMMENTS_POST_COMMENT_ERROR = 'COMMENTS_POST_COMMENT_ERROR';
