// flow-typed signature: 3cf68fbff43f0b14f6eb1b99b609a139
// flow-typed version: <<STUB>>/bulma_v^0.7.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
