// flow-typed signature: 147d8afe49f0423acc4f8cac04231a28
// flow-typed version: <<STUB>>/bulma-accordion_v^2.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-accordion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-accordion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bulma-accordion/dist/js/bulma-accordion' {
  declare module.exports: any;
}

declare module 'bulma-accordion/dist/js/bulma-accordion.min' {
  declare module.exports: any;
}

declare module 'bulma-accordion/src/js/events' {
  declare module.exports: any;
}

declare module 'bulma-accordion/src/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bulma-accordion/dist/js/bulma-accordion.js' {
  declare module.exports: $Exports<'bulma-accordion/dist/js/bulma-accordion'>;
}
declare module 'bulma-accordion/dist/js/bulma-accordion.min.js' {
  declare module.exports: $Exports<'bulma-accordion/dist/js/bulma-accordion.min'>;
}
declare module 'bulma-accordion/src/js/events.js' {
  declare module.exports: $Exports<'bulma-accordion/src/js/events'>;
}
declare module 'bulma-accordion/src/js/index.js' {
  declare module.exports: $Exports<'bulma-accordion/src/js/index'>;
}
